require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FinanzsController do

  # This should return the minimal set of attributes required to create a valid
  # Finanz. As you add validations to Finanz, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "Title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FinanzsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all finanzs as @finanzs" do
      finanz = Finanz.create! valid_attributes
      get :index, {}, valid_session
      assigns(:finanzs).should eq([finanz])
    end
  end

  describe "GET show" do
    it "assigns the requested finanz as @finanz" do
      finanz = Finanz.create! valid_attributes
      get :show, {:id => finanz.to_param}, valid_session
      assigns(:finanz).should eq(finanz)
    end
  end

  describe "GET new" do
    it "assigns a new finanz as @finanz" do
      get :new, {}, valid_session
      assigns(:finanz).should be_a_new(Finanz)
    end
  end

  describe "GET edit" do
    it "assigns the requested finanz as @finanz" do
      finanz = Finanz.create! valid_attributes
      get :edit, {:id => finanz.to_param}, valid_session
      assigns(:finanz).should eq(finanz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Finanz" do
        expect {
          post :create, {:finanz => valid_attributes}, valid_session
        }.to change(Finanz, :count).by(1)
      end

      it "assigns a newly created finanz as @finanz" do
        post :create, {:finanz => valid_attributes}, valid_session
        assigns(:finanz).should be_a(Finanz)
        assigns(:finanz).should be_persisted
      end

      it "redirects to the created finanz" do
        post :create, {:finanz => valid_attributes}, valid_session
        response.should redirect_to(Finanz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved finanz as @finanz" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanz.any_instance.stub(:save).and_return(false)
        post :create, {:finanz => { "Title" => "invalid value" }}, valid_session
        assigns(:finanz).should be_a_new(Finanz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Finanz.any_instance.stub(:save).and_return(false)
        post :create, {:finanz => { "Title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested finanz" do
        finanz = Finanz.create! valid_attributes
        # Assuming there are no other finanzs in the database, this
        # specifies that the Finanz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Finanz.any_instance.should_receive(:update_attributes).with({ "Title" => "MyString" })
        put :update, {:id => finanz.to_param, :finanz => { "Title" => "MyString" }}, valid_session
      end

      it "assigns the requested finanz as @finanz" do
        finanz = Finanz.create! valid_attributes
        put :update, {:id => finanz.to_param, :finanz => valid_attributes}, valid_session
        assigns(:finanz).should eq(finanz)
      end

      it "redirects to the finanz" do
        finanz = Finanz.create! valid_attributes
        put :update, {:id => finanz.to_param, :finanz => valid_attributes}, valid_session
        response.should redirect_to(finanz)
      end
    end

    describe "with invalid params" do
      it "assigns the finanz as @finanz" do
        finanz = Finanz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanz.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanz.to_param, :finanz => { "Title" => "invalid value" }}, valid_session
        assigns(:finanz).should eq(finanz)
      end

      it "re-renders the 'edit' template" do
        finanz = Finanz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Finanz.any_instance.stub(:save).and_return(false)
        put :update, {:id => finanz.to_param, :finanz => { "Title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested finanz" do
      finanz = Finanz.create! valid_attributes
      expect {
        delete :destroy, {:id => finanz.to_param}, valid_session
      }.to change(Finanz, :count).by(-1)
    end

    it "redirects to the finanzs list" do
      finanz = Finanz.create! valid_attributes
      delete :destroy, {:id => finanz.to_param}, valid_session
      response.should redirect_to(finanzs_url)
    end
  end

end
